### ISSUE TITLE
Wrong added section to rockcraft.yaml

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/prometheus-pushgateway-rock#4]
Seems like [`rock-update.yaml`](https://github.com/canonical/observability/blob/main/.github/workflows/rock-update.yaml) workflow is adding an extra section to `rockcraft.yaml` that breaks `rockcraft pack` command.

For instance this is is the [original `rockcraft.yaml`](https://github.com/canonical/prometheus-pushgateway-rock/blob/main/1.6.0/rockcraft.yaml), and this is [the new one](https://github.com/canonical/prometheus-pushgateway-rock/pull/2/files#diff-458bb559a02c9a3b926710a7debf4f94685a7e8603cff3bd8d6b20abfcfd72bbR31-R33)

The added section is:

```yaml
  prometheus-pushgateway:
    source-tag: v1.6.1
    build-snaps: go/1.19/stable
```
